version: '2'
services:
  clamav:
    build: .
    ports:
      - "3010"
  clamav-rest:
    build:
      context: ./clamav-rest
    environment:
      - HOST=clamav
    links:
      - clamav
    ports:
      - "8080:8080"